### ISSUE TITLE
[ERROR] Difficulty Change - Disables plugin on startup

### ISSUE THREAD

**Issue by frosxt** [NikV2/AliceAPI#2]
**Discord**
frost#0723
I'm not verified on your discord, I wasn't the one who purchased the plugin, it was my partner, however I do the development work so I usually deal with issues, please still listen to this and disregard that.

**Error(s)**
https://pastebin.com/ACbT2BHX

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Is ProtocolLib up to date?**
Yes

**Server Environment & Version**
TacoSpigot 1.8.8 (SpaceDeltaSpigot for full specifics)

**Additional Information (Optional)**

**Comment by NikV2** [comment]
Hey there, you need to update ProtocolLib.

Use the latest build from jenkins.
