### ISSUE TITLE
[FALSE POSITIVE]

### ISSUE THREAD

**Issue by XReioX** [NikV2/AliceAPI#21]
**Discord**
Provide your Discord username and ID (ie: User#4252)
Make sure you're Verified on our Discord otherwise this will
Be marked as Invalid.
hinoob#8910
If the false positive was found on our Test Server, You may leave this empty

**What client triggered the false positive?**
The client's name, IE Vanilla or Sigma (False Positives reported by Bad PvP clients will be marked as Invalid)
Vanilla

**Verbose Messages**
The verbose messages that showed up by using /Alice Verbose (Must be in a Pastebin link or similar)
https://imgur.com/a/BqHKqCr

**Video (Recommended)**
A video showing the false positive in action (https://streamable.com/ or from any other source where the video is non public)

**Is the plugin up to date?**
Yes/No
Yes

**Is ProtocolLib up to date?**
Yes/No
Yes

**Server Environment & Version**
Your server software (ie Paper 1.12.2)
1.8.8 PaperSpigot

**To reproduce**
Some more information on how to Reproduce the false positive
After a botpvp match with StrikePractice, you teleport, and then it falses Fly E, and Fly D

**Comment by Izibane** [comment]
Nik not handling teleports? 😳

**Comment by NikV2** [comment]
if (teleport) flag();
