### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GardeningTool** [NikV2/AliceAPI#22]
**Discord**
Provide your Discord username and ID (ie: User#4252) Nik#6510
Make sure you're Verified on our Discord otherwise this will ok
Be marked as Invalid. ok x2

**Describe the bug**

i forgot

**To Reproduce**
Steps to reproduce the behavior.

idk try ti for urself

**Does the issue still persist on the default config?**
Yes/No

maybe??? idfk

**Is the plugin up to date?**
Yes/No

how do i check

**Is ProtocolLib up to date?**
Yes/No

packegevnets ie bterter

**Server Environment & Version**
Your server software (ie Paper 1.12.2)

clubspigot 1./89.9

**Additional Information (Optional)**

idk i forgot lol

**Comment by NikV2** [comment]
Thank you, i'll have it fixed in the next update. feel free to revert for now until i fix it.

no refunds btw

**Comment by GardeningTool** [comment]
many fanks

newb
