### ISSUE TITLE
[BYPASS] NoFall - Wurst Client

### ISSUE THREAD

**Issue by MackenzieMolloy** [NikV2/AliceAPI#3]
**Discord**
Mackenzie Molloy#1821

If the bypass was found on our Test Server, You may leave this empty

**Client That Bypassed**
Wurst Client

**Cheat That Bypassed**
NoFall

**Video (Recommended)**
None

**Does the Bypass still persist on default checks.yml?**
Yes

**Is the plugin up to date?**
Yes

**Is ProtocolLib up to date?**
Yes

**Server Environment & Version**
Paper 1.16.5

**Additional Information (Optional)**
None

**Comment by NikV2** [comment]
Sorry i can't reproduce, seems to work fine for me.

Make sure u got a valid height and i'd suggest u try on an actual server instead of LocalHost.
