### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by Tobies** [NikV2/AliceAPI#4]
**Discord**
White - Roei#6441

**Error(s)**
Provide a Pastebin link with your error.
https://pastebin.com/kuDGYiSD

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Is ProtocolLib up to date?**
Yes

**Server Environment & Version**
Purpur 1.16.5

**Additional Information (Optional)**

**Comment by NikV2** [comment]
Seems like a mistake on my end, This has been fixed in the upcoming recoded version.

Until it's up, I'd suggest you change the executor type in the config.yml to *SINGLE*. Which should hopefully fix this error for now.
