### ISSUE TITLE
[BYPASS]

### ISSUE THREAD

**Issue by FINE-V3rm** [NikV2/AliceAPI#46]
**Discord**
Provide your Discord username and ID (ie: User#4252)
Make sure you're Verified on our Discord otherwise this will
Be marked as Invalid.

If the bypass was found on our Test Server, You may leave this empty

**Client That Bypassed**
Trigger client

**Cheat That Bypassed**
Optifine fast math

**Video (Recommended)**
Shut up

**Does the Bypass still persist on default checks.yml?**
No

**Is the plugin up to date?**
No

**Is ProtocolLib up to date?**
No

**Server Environment & Version**
Craftbukkit 1.5.2

**Additional Information (Optional)**
There are black pepole on my server

**Comment by NikV2** [comment]
Has already been reported.

**Comment by FINE-V3rm** [comment]
Thank you, please remove the blacks on my server.


Good luck my jigga!

**Comment by FINE-V3rm** [comment]
Edit: Removed the blacks from my server using the INSANE Alice API(tm) thanks Nik!
