### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by Tobies** [NikV2/AliceAPI#5]
**Discord**
White - Roei#6441

**Error(s)**
https://pastebin.com/ZiZLmqE4

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Is ProtocolLib up to date?**
Yes

**Server Environment & Version**
purpur 1.16.5

**Additional Information (Optional)**

**Comment by NikV2** [comment]
Try turning off KillAura (Accuracy) within the checks.yml or making alice Singlethreaded within the config until the new version is up.
That should fix em.
I apologize!
