### ISSUE TITLE
Randomly disconnects players [BUG]

### ISSUE THREAD

**Issue by PestAnaLiz** [NikV2/AliceAPI#50]
**Describe the bug**
Hello. After one of the recent Alice updates, I ran into the problem: Alice randomly disconnects players on my server with timeout reason. We have been looking for the reason for a long time, but from the latest changes there was only an alice update. After removing the plugin from the server, the disconnections stopped.

**Is the plugin up to date?**
Yes

**Is ProtocolLib up to date?**
Yes

**Server Environment & Version**
Paper 1.12.2

**Comment by NikV2** [comment]
Hey there, im guessing that happens mostly on bedrock players.

For the time being disable the timeout_teleport and timeout_communication options in the config.yml and re-enable them once the recode is finished

**Comment by PestAnaLiz** [comment]
> Hey there, im guessing that happens mostly on bedrock players.

Not. We do not use Geyser or anything similar.

**Comment by PestAnaLiz** [comment]
Unfortunately, this still happens after turning off these two functions. Now it happens less often, but it still continues to happen.
