### ISSUE TITLE
Alerts [REQUEST]

### ISSUE THREAD

**Issue by PestAnaLiz** [NikV2/AliceAPI#51]
**What feature would you like to be added and why?**
Allow use `/alice alerts` command through the console please

**Comment by NikV2** [comment]
I don't think that's possible with the way alice handles alerts currently, It's players only but if i find a way to do it in the future i will!

**Comment by PestAnaLiz** [comment]
Maybe you just add an option in the config to duplicate alerts to the server log? Well, or at least duplicate in the server log those messages that are written in data.yml
