### ISSUE TITLE
Reach, HitBox [FALSE POSITIVE]

### ISSUE THREAD

**Issue by PestAnaLiz** [NikV2/AliceAPI#54]
**What client triggered the false positive?**
Vanilla

**Verbose Messages**
https://pastebin.com/TTfkbzty

**Is the plugin up to date?**
Yes

**Is ProtocolLib up to date?**
Yes

**Server Environment & Version**
Paper 1.12.2

**To reproduce**
If you hit npc (citizens), you can get false positives. This does not always happen, but sometimes you can get into such a position that each hit will falsely trigger alice. It is difficult to repeat this, but it would be logical to simply exclude such entities from the check, or add an option to the config so that we can choose that checks should only respond to real players.

**Comment by NikV2** [comment]
Thanks!

**Comment by NikV2** [comment]
I can't seem to reproduce it on my jar, maybe it's an issue with the current build.

Let me know if it still happens once the recode is up.

**Comment by NikV2** [comment]
@PestAnaLiz A video would be highly appreciated! so i can test it on my build.
