### ISSUE TITLE
[BYPASS] KillAura

### ISSUE THREAD

**Issue by mrchomik892** [NikV2/AliceAPI#62]
**Discord**
Provide your Discord username and ID (ie: User#4252)
Make sure you're Verified on our Discord otherwise this will
Be marked as Invalid.
żaba#1274
If the bypass was found on our Test Server, You may leave this empty

**Client That Bypassed**
Provide the name of the client, And a link where we can download it from.
Sigma Client (https://sigmaclient.info)
**Cheat That Bypassed**
The module name that Bypassed Alice And optionally the settings
KillAura
**Video (Recommended)**
A video showing the false positive in action (https://streamable.com/ or from any other source where the video is non public)

**Does the Bypass still persist on default checks.yml?**
Yes/No
Yes, i never changed the config
**Is the plugin up to date?**
Yes/No
Yes, 
![image](https://sharex.download/uploads/31406b56-5a9f-486f-b94d-beae4d361fc9/CZAtBEzN_.png)

**Is ProtocolLib up to date?**
Yes/No
Yes
**Server Environment & Version**
Your server software (ie Paper 1.12.2)
Old Tuinity 1.16.5
**Additional Information (Optional)**
Some more information on how to Bypass
![image](https://user-images.githubusercontent.com/54484477/120612658-b4d42b80-c455-11eb-8e98-3161505a6608.png)
![image](https://user-images.githubusercontent.com/54484477/120612691-be5d9380-c455-11eb-87dc-4befce0126ae.png)

~~PS: Reach does work~~

**Comment by mrchomik892** [comment]
Pays.host link: https://sharex.download/uploads/31406b56-5a9f-486f-b94d-beae4d361fc9/DKJtBpSW_.mp4

**Comment by NikV2** [comment]
That was 3 hits, Plus try on an actual server.

**Comment by 24Marzo** [comment]
you need multiple hits to flag aim check

**Comment by NikV2** [comment]
**Edit**

Rotations mode: None makes it so it simply attacks the entity u're looking at, it does not rotate.

**Comment by mrchomik892** [comment]
> That was 3 hits, Plus try on an actual server.
> 
> Alice does not perform well on localhost

it was on actual server

**Comment by mrchomik892** [comment]
ok i will try

**Comment by mrchomik892** [comment]
yeah, it did still bypass...

**Comment by mrchomik892** [comment]
https://sharex.download/uploads/31406b56-5a9f-486f-b94d-beae4d361fc9/BXVpIUqG_.gif

**Comment by mrchomik892** [comment]
https://youtu.be/hHM04TJwBfg
