### ISSUE TITLE
[BUG] Killaura bot isn't destroyed on disable

### ISSUE THREAD

**Issue by Izibane** [NikV2/AliceAPI#65]
isnt worse bug but still a bug

**Discord**
Provide your Discord username and ID (ie: User#4252) izibane#6557
Make sure you're Verified on our Discord otherwise this will
Be marked as Invalid.

**Describe the bug**
Bot isnt removed when disabling the plugin so is infinitely stuck here until player relogs

![image](https://user-images.githubusercontent.com/77923336/120939682-a9f4f180-c708-11eb-8fdf-1f0bece2ad5c.png)

**To Reproduce**
Steps to reproduce the behavior.
Force stop the plugin whether through plugman or a crash

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Is ProtocolLib up to date?**
Yes

**Server Environment & Version**
Your server software (ie Paper 1.12.2)
1.8 | viaversion

**Comment by mrchomik892** [comment]
Prob invalid - Alice is NOT COMPATIBLE with plugman and any plugin managers.

**Comment by steviebeenz** [comment]
**Force stop the plugin** whether through plugman or a **crash**

**Comment by 24Marzo** [comment]
kill @e

**Comment by NikV2** [comment]
It's fine, it's my mistake. I'll have it fixed

Thanks for letting me know!
