### ISSUE TITLE
[BYPASS] Elytra Fly

### ISSUE THREAD

**Issue by tangerine349** [NikV2/AliceAPI#7]
**Discord**
Provide your Discord username and ID Orange#0513 339839989552775179
Make sure you're Verified on our Discord otherwise this will
Be marked as Invalid. (I posted my verify purchase message but im not verifyed yet)

If the bypass was found on our Test Server, You may leave this empty

**Client That Bypassed**
Impact

**Cheat That Bypassed**
This can be used to bypass elytra fly - Using Air Jump while flying with an elytra (Looking to far down will set off alerts but if youre careful you wont be flagged, or if you go to fast you get flagged)

**Video (Recommended)**
A video showing the false positive in action (https://streamable.com/ or from any other source where the video is non public)
https://youtu.be/zqg51WBk0EU

**Does the Bypass still persist on default checks.yml?**
Yes

**Is the plugin up to date?**
Yes

**Is ProtocolLib up to date?**
Yes

**Server Environment & Version**
Paper 1.16.5

**Additional Information (Optional)**
Turn on Air Jump on impact and use an elytra, if you do it right you can bypass

**Comment by NikV2** [comment]
Hi there!

The video seems to not be up anymore.

**Comment by NikV2** [comment]
I managed to reproduce though, Thanks for your report!

Right now once im focusing more on stability and making the current checks better. Once that gets done i'll add better elytra checks since the two alice has right now are kind of sus.
