### ISSUE TITLE
[REQUEST] Client Detector

### ISSUE THREAD

**Issue by TAKKIRU** [NikV2/AliceAPI#75]
Здравствуйте, я из России и моё знание английского низкое, меня интересует вопрос, как добавить читклиент Aristois в фильтр запрещённых клиентов? Расскажите по подробнее, можно на английском я переведу.

**Comment by TAKKIRU** [comment]
Наш проект попробовал античит Spartan и Matrix, к сожалению оба плагина полная хрень, ложные срабатывания и так далее, во время тестирования Alice не было ложных срабатываний а только реальные! По этому мы хотим использовать данный античит, он лучший!

**Comment by TAKKIRU** [comment]
Мы пытались его купить но купить его не где нельзя, нашли слитую версию но и этому рады!

**Comment by TAKKIRU** [comment]
Так-же я пытался связаться с разработчиком Алисы но так и не смог найти способ связи с ним, вот и пишу тут.

**Comment by NikV2** [comment]
What the hell

**Comment by TAKKIRU** [comment]
Plis translite my message to russia

**Comment by TAKKIRU** [comment]
Как можно с вами связаться? Для личного диалога.
